language: php

matrix:
    include:
        - php: 5.5
    fast_finish: true

env:
    global:
        - components=no

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini
    - sudo locale-gen fr_FR.UTF-8 && sudo update-locale
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - export COMPOSER_ROOT_VERSION=2.3.x-dev

install:
    - composer --prefer-source --dev install

script:
    - phpunit --filter testSimilarBehaviorBetweenSubmitAndHandleRequestWhenPassingRequest
